In [1]:
# import numpy library as np
import numpy as np

In [2]:
# Creating Arrays

arr1 = np.array([4,5,7,8])
print(arr1)
print(arr1[2])

arr2 = np.zeros(5)
print(arr2)

arr3 = np.ones(5)
print(arr3)

arr4 = np.empty(5)
print(arr4)


[4 5 7 8]
7
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]


In [6]:
# Array Attributes:
arr = np.array([4, 6, 8, 4, 22, 75])
print(np.shape(arr))

(6,)


In [11]:
list_num = [[3, 5, 2], [4, 7, 3]]
arr = np.array(list_num)
print(np.ndim(arr))


2


In [15]:
np.dtype(np.int16)

dtype('int16')

In [16]:
np.size(arr)

6

In [23]:
print(type(arr))
# arr.size(arr)

<class 'numpy.ndarray'>


In [17]:
arr.min()

2

In [24]:
arr.max()

7

In [25]:
arr.sum()

24

In [26]:
arr.mean()

4.0

In [27]:
arr.std()

1.632993161855452

In [30]:
a = np.array([3,5,7,8])
b = np.array([7,5,6,3])

a.dot(b)


112

In [37]:
list_num = [[3, 5, 2], [4, 7, 3]]
arr = np.array(list_num)
print(arr)
print()
print(arr.transpose())

[[3 5 2]
 [4 7 3]]

[[3 4]
 [5 7]
 [2 3]]


In [58]:
# Array Slicing and Indexing:
list_1d = [3,4, 5, 6, 7, 8, 9, 0]
arr = np.array(list_1d)
print(arr[4])
print(arr[3])
print(arr[[3, 7]])
print(arr[3 : 7])
print(arr[3 : 7 : 2])
print(arr[ : 3 : 2])
print(arr[ :  : 2])
print(arr[ 4:  : 2])
# ndarray[start:stop:step]

7
6
[6 0]
[6 7 8 9]
[6 8]
[3 5]
[3 5 7 9]
[7 9]


In [65]:
# Array Concatenation and Stacking:
a = np.array([4, 6, 7, 8, 9])
b = np.array([54, 34, 67])
print(np.concatenate((a,b)))

a = np.array([4, 6, 7, 9])
b = np.array([54, 34, 67])
# np.concatenate((a,b), axis=1) #https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

[ 4  6  7  8  9 54 34 67]


In [66]:
np.vstack(a)

array([[4],
       [6],
       [7],
       [9]])

In [68]:
np.hstack(a)

array([4, 6, 7, 9])

In [ ]:
# Array Broadcasting:

# NumPy allows you to perform operations on arrays of different shapes through broadcasting.


In [112]:

# Create a 2x3 array
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Create a 1x3 array
array2 = np.array([10, 20, 30])

# Add the two arrays using broadcasting
result = array1 + array2
print(type(result))
print(result)

<class 'numpy.ndarray'>
[[11 22 33]
 [14 25 36]]


In [69]:
# Mathematical Functions:
np.sin(a)

array([-0.7568025 , -0.2794155 ,  0.6569866 ,  0.41211849])

In [70]:
np.cos(a)

array([-0.65364362,  0.96017029,  0.75390225, -0.91113026])

In [71]:
np.exp(a)

array([  54.59815003,  403.42879349, 1096.63315843, 8103.08392758])

In [84]:
np.tan(a)

array([ 1.15782128, -0.29100619,  0.87144798, -0.45231566])

In [86]:
np.arcsin(np.sin(a))

array([-0.85840735, -0.28318531,  0.71681469,  0.42477796])

In [87]:
np.arccos(np.cos(a))

array([2.28318531, 0.28318531, 0.71681469, 2.71681469])

In [88]:
np.arctan(np.tan(a))

array([ 0.85840735, -0.28318531,  0.71681469, -0.42477796])

In [72]:
np.log(a)

array([1.38629436, 1.79175947, 1.94591015, 2.19722458])

In [77]:
print(a)
print(np.add(a, 100))

[4 6 7 9]
[104 106 107 109]


In [79]:
print(a)
print(np.subtract(a, 100))

[4 6 7 9]
[-96 -94 -93 -91]


In [81]:
print(a)
print(np.multiply(a, 100))

[4 6 7 9]
[400 600 700 900]


In [82]:
print(a)
print(np.divide(a, 100))

[4 6 7 9]
[0.04 0.06 0.07 0.09]


In [89]:
np.degrees(a)

array([229.18311805, 343.77467708, 401.07045659, 515.66201562])

In [90]:
np.radians(a)

array([0.06981317, 0.10471976, 0.12217305, 0.15707963])

In [92]:
# https://www.programiz.com/python-programming/numpy/math-functions

In [93]:
# Random Number Generation:

In [94]:
print(np.random.rand())

0.9795074223290935


In [95]:
print(np.random.randn())


0.44850242798337575


In [97]:
print(np.random.randint(10))


2


In [98]:
print(np.random.randint(10))


4


In [100]:
print(np.random.seed(12))


None


In [103]:
# Linear Algebra:
matr = [[3, 4, 5, 7], [5, 6, 7, 8], [5, 3, 6, 2], [2, 1, 5, 7]]

m = np.array(matr)
np.linalg.inv(m)

array([[-13.1,   9.6,  -2.7,   2.9],
       [  4.7,  -3.2,   0.9,  -1.3],
       [  9.9,  -7.4,   2.3,  -2.1],
       [ -4. ,   3. ,  -1. ,   1. ]])

In [104]:
np.linalg.det(matr)

-9.99999999999993

In [105]:
np.linalg.eig(matr)

EigResult(eigenvalues=array([18.01754886+0.j        , -0.07356661+0.j        ,
        2.02800888+1.85244688j,  2.02800888-1.85244688j]), eigenvectors=array([[-0.48444376+0.j        , -0.75202037+0.j        ,
        -0.31024942+0.17169189j, -0.31024942-0.17169189j],
       [-0.68044499+0.j        ,  0.26367487+0.j        ,
        -0.1032407 +0.33725028j, -0.1032407 -0.33725028j],
       [-0.42871242+0.j        ,  0.56190033+0.j        ,
         0.68714234+0.j        ,  0.68714234-0.j        ],
       [-0.34425939+0.j        , -0.22183092+0.j        ,
        -0.43417705-0.29865781j, -0.43417705+0.29865781j]]))

In [107]:
# Statistical Functions:
np.mean(a)

6.5

In [108]:
np.median(a)

6.5

In [109]:
np.var(a)

3.25

In [110]:
np.std(a)

1.8027756377319946

In [1]:
import numpy as np

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [4]:
np.arange(4, 20, 5)

array([ 4,  9, 14, 19])

In [6]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [7]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [8]:
np.logspace(1,2, num=10)

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [16]:
a = [[4, 6], [5, 7], [8, 4]]
n = np.array(a)
n.shape # This array attribute return a tuple consisting of array dimensions.

(3, 2)

In [17]:
n.ndim # This array attribute returns the number of array dimensions.

2

In [18]:
n.itemsize # This attribute returns the length of each element of array in bytes.

4

In [19]:
n.flags # The function return the current value of a set of flages.

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [63]:
r1 = np.random.rand()
print(r1)
r2 = np.random.rand(3, 4)
print(r2)
# here, in rand fucntion generated number is less then 1.

0.42317975130381613
[[0.531678   0.25633832 0.75809287 0.51473875]
 [0.32623278 0.58691568 0.76169489 0.21864733]
 [0.16985379 0.77548377 0.06550343 0.44640134]]


In [64]:
r1 = np.random.randn()
print(r1)
r2 = np.random.randn(3, 4)
print(r2)
# here generated number is may greater then |1|

-0.814737579139471
[[-1.35670265  1.96824914 -0.73156215 -0.91570755]
 [-0.38732615 -0.98672044  0.80132271 -0.51375875]
 [ 2.79631522  0.56909676 -0.15538912 -0.69271064]]


In [65]:
np.random.randint(6) # random integer in between 0 to 6  (include 0 and not 6)

0

In [66]:
np.random.randint(6, 10) # random integer in between 0 to 6  (include 6 and not 10)

8

In [67]:
np.random.randint(4, 12, 5) # ndarray of 5 random integer in between 4 to 12  (include 4 and not 12)

array([ 6,  6, 11,  9,  8])

In [68]:
dir(np.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_bit_generator',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_bit_generator',
 'set_state',
 'shuf

In [81]:
# This is a aggregations functions like np.min, np.max, np.mean, np.median, np.sum, np.prod etc.....
# Some of them is given below, which is not mension above...
a = np.random.randint(-10, 12, 5)
a

array([ 6, -4, 10, -6, -2])

In [83]:
np.cumsum(a)

array([ 6,  2, 12,  6,  4])

In [84]:
np.argmax(a)

2

In [85]:
np.max(a)

10

In [86]:
# Indexing and Slicing

In [100]:
a = np.arange(2, 20, 2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [126]:
print(a[2])
# print(a[2, 4]) # Error, As it is not 2d array
print(a[[2, 4]]) # This is work
print(a[[True, True, True, False, False, True, False, True, False]]) 
print(a[2:4])
print(a[5:8])
print(a[4:])
print(a[:6])
print(a[2:8:3])
print(a[2:8:1])
print(a[4:9:3])
print(a[-1])
print(a[-5])
print(a>10)
print(a[a>10])
print(a[a<=10])

6
[ 6 10]
[ 2  4  6 12 16]
[6 8]
[12 14 16]
[10 12 14 16 18]
[ 2  4  6  8 10 12]
[ 6 12]
[ 6  8 10 12 14 16]
[10 16]
18
10
[False False False False False  True  True  True  True]
[12 14 16 18]
[ 2  4  6  8 10]


In [127]:
a = [["a", "b", "c"], ["d", "e", "f"], ["g", "h", "i"]]
n = np.array(a)
n

array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['g', 'h', 'i']], dtype='<U1')

In [128]:
n[0:2, 0:2]

array([['a', 'b'],
       ['d', 'e']], dtype='<U1')

In [129]:
n[2:, 2:]

array([['i']], dtype='<U1')

In [130]:
n[1:, 2:]

array([['f'],
       ['i']], dtype='<U1')

In [131]:
n[2:, 1:]

array([['h', 'i']], dtype='<U1')

In [132]:
n[1:, :2]

array([['d', 'e'],
       ['g', 'h']], dtype='<U1')

In [133]:
n[-1, -1]

'i'

In [134]:
n[-1, -2]

'h'

In [135]:
n[::-1, ::-1] # Complete reverse

array([['i', 'h', 'g'],
       ['f', 'e', 'd'],
       ['c', 'b', 'a']], dtype='<U1')

In [138]:
n[::1,::-1] # reverse like row c, b, a

array([['c', 'b', 'a'],
       ['f', 'e', 'd'],
       ['i', 'h', 'g']], dtype='<U1')

In [140]:
n[::-1, ::1] # reverse like first row is g, h, i

array([['g', 'h', 'i'],
       ['d', 'e', 'f'],
       ['a', 'b', 'c']], dtype='<U1')