Certainly! Let's explore the **`np.full`** and **`np.eye`** functions in **NumPy**:

1. **`np.full`**:
   - The **`np.full`** function creates a new array with a specified shape and fills it with a given value.
   - Syntax: `np.full(shape, fill_value, dtype=None, order='C')`
   - Parameters:
     - `shape`: An integer or a sequence of integers representing the shape of the new array (e.g., `(2, 3)` or `2`).
     - `fill_value`: The value with which to fill the array.
     - `dtype`: Optional data type of the array (default is `None`).
     - `order`: Optional parameter specifying the memory layout (either `'C'` for row-major or `'F'` for column-major).
   - Example:
     ```python
     import numpy as np
     arr = np.full((3, 4), 5)  # Creates a 3x4 array filled with 5
     ```

2. **`np.eye`**:
   - The **`np.eye`** function returns a 2-D array with ones on the diagonal and zeros elsewhere.
   - Syntax: `np.eye(N, M=None, k=0, dtype=float, order='C', like=None)`
   - Parameters:
     - `N`: Number of rows in the output.
     - `M`: Optional number of columns (defaults to `N` if not specified).
     - `k`: Index of the diagonal (0 for the main diagonal, positive for upper diagonals, negative for lower diagonals).
     - `dtype`: Optional data type (default is `float`).
     - `order`: Memory layout ('C' or 'F').
   - Example:
     ```python
     import numpy as np
     identity_matrix = np.eye(3)  # Creates a 3x3 identity matrix
     ```

Remember, **`np.full`** lets you create an array filled with a specific value, while **`np.eye`** generates an identity matrix with ones on the diagonal. Both functions are powerful tools for array creation in NumPy! 🚀

For more details, you can refer to the [official NumPy documentation](https://numpy.org/doc/stable/reference/generated/numpy.full.html) and the [NumPy eye documentation](https://numpy.org/doc/stable/reference/generated/numpy.eye.html) ¹⁵..

Source: Conversation with Bing, 4/4/2024
(1) numpy.eye — NumPy v1.26 Manual. https://numpy.org/doc/stable/reference/generated/numpy.eye.html.
(2) numpy.full — NumPy v1.26 Manual. https://numpy.org/doc/stable/reference/generated/numpy.full.html.
(3) What are the advantages of using numpy.identity over numpy.eye?. https://stackoverflow.com/questions/28363447/what-are-the-advantages-of-using-numpy-identity-over-numpy-eye.
(4) How to use numpy.eye function with custom diagonal values?. https://stackoverflow.com/questions/73324186/how-to-use-numpy-eye-function-with-custom-diagonal-values.
(5) NumPy: numpy.full() function - w3resource. https://www.w3resource.com/numpy/array-creation/full.php.
(6) en.wikipedia.org. https://en.wikipedia.org/wiki/NumPy.

In [3]:
import numpy as np

a = np.full((4,5), 6)
print(a)


[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]


In [4]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])