In [1]:
# import numpy library as np
import numpy as np

In [2]:
# Creating Arrays

arr1 = np.array([4,5,7,8])
print(arr1)
print(arr1[2])

arr2 = np.zeros(5)
print(arr2)

arr3 = np.ones(5)
print(arr3)

arr4 = np.empty(5)
print(arr4)


[4 5 7 8]
7
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]


In [6]:
# Array Attributes:
arr = np.array([4, 6, 8, 4, 22, 75])
print(np.shape(arr))

(6,)


In [11]:
list_num = [[3, 5, 2], [4, 7, 3]]
arr = np.array(list_num)
print(np.ndim(arr))


2


In [15]:
np.dtype(np.int16)

dtype('int16')

In [16]:
np.size(arr)

6

In [23]:
print(type(arr))
# arr.size(arr)

<class 'numpy.ndarray'>


In [17]:
arr.min()

2

In [24]:
arr.max()

7

In [25]:
arr.sum()

24

In [26]:
arr.mean()

4.0

In [27]:
arr.std()

1.632993161855452

In [30]:
a = np.array([3,5,7,8])
b = np.array([7,5,6,3])

a.dot(b)


112

In [37]:
list_num = [[3, 5, 2], [4, 7, 3]]
arr = np.array(list_num)
print(arr)
print()
print(arr.transpose())

[[3 5 2]
 [4 7 3]]

[[3 4]
 [5 7]
 [2 3]]


In [58]:
# Array Slicing and Indexing:
list_1d = [3,4, 5, 6, 7, 8, 9, 0]
arr = np.array(list_1d)
print(arr[4])
print(arr[3])
print(arr[[3, 7]])
print(arr[3 : 7])
print(arr[3 : 7 : 2])
print(arr[ : 3 : 2])
print(arr[ :  : 2])
print(arr[ 4:  : 2])
# ndarray[start:stop:step]

7
6
[6 0]
[6 7 8 9]
[6 8]
[3 5]
[3 5 7 9]
[7 9]


In [65]:
# Array Concatenation and Stacking:
a = np.array([4, 6, 7, 8, 9])
b = np.array([54, 34, 67])
print(np.concatenate((a,b)))

a = np.array([4, 6, 7, 9])
b = np.array([54, 34, 67])
# np.concatenate((a,b), axis=1) #https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

[ 4  6  7  8  9 54 34 67]


In [66]:
np.vstack(a)

array([[4],
       [6],
       [7],
       [9]])

In [68]:
np.hstack(a)

array([4, 6, 7, 9])

In [ ]:
# Array Broadcasting:

# NumPy allows you to perform operations on arrays of different shapes through broadcasting.


In [112]:

# Create a 2x3 array
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Create a 1x3 array
array2 = np.array([10, 20, 30])

# Add the two arrays using broadcasting
result = array1 + array2
print(type(result))
print(result)

<class 'numpy.ndarray'>
[[11 22 33]
 [14 25 36]]


In [69]:
# Mathematical Functions:
np.sin(a)

array([-0.7568025 , -0.2794155 ,  0.6569866 ,  0.41211849])

In [70]:
np.cos(a)

array([-0.65364362,  0.96017029,  0.75390225, -0.91113026])

In [71]:
np.exp(a)

array([  54.59815003,  403.42879349, 1096.63315843, 8103.08392758])

In [84]:
np.tan(a)

array([ 1.15782128, -0.29100619,  0.87144798, -0.45231566])

In [86]:
np.arcsin(np.sin(a))

array([-0.85840735, -0.28318531,  0.71681469,  0.42477796])

In [87]:
np.arccos(np.cos(a))

array([2.28318531, 0.28318531, 0.71681469, 2.71681469])

In [88]:
np.arctan(np.tan(a))

array([ 0.85840735, -0.28318531,  0.71681469, -0.42477796])

In [72]:
np.log(a)

array([1.38629436, 1.79175947, 1.94591015, 2.19722458])

In [77]:
print(a)
print(np.add(a, 100))

[4 6 7 9]
[104 106 107 109]


In [79]:
print(a)
print(np.subtract(a, 100))

[4 6 7 9]
[-96 -94 -93 -91]


In [81]:
print(a)
print(np.multiply(a, 100))

[4 6 7 9]
[400 600 700 900]


In [82]:
print(a)
print(np.divide(a, 100))

[4 6 7 9]
[0.04 0.06 0.07 0.09]


In [89]:
np.degrees(a)

array([229.18311805, 343.77467708, 401.07045659, 515.66201562])

In [90]:
np.radians(a)

array([0.06981317, 0.10471976, 0.12217305, 0.15707963])

In [92]:
# https://www.programiz.com/python-programming/numpy/math-functions

In [93]:
# Random Number Generation:

In [94]:
print(np.random.rand())

0.9795074223290935


In [95]:
print(np.random.randn())


0.44850242798337575


In [97]:
print(np.random.randint(10))


2


In [98]:
print(np.random.randint(10))


4


In [100]:
print(np.random.seed(12))


None


In [103]:
# Linear Algebra:
matr = [[3, 4, 5, 7], [5, 6, 7, 8], [5, 3, 6, 2], [2, 1, 5, 7]]

m = np.array(matr)
np.linalg.inv(m)

array([[-13.1,   9.6,  -2.7,   2.9],
       [  4.7,  -3.2,   0.9,  -1.3],
       [  9.9,  -7.4,   2.3,  -2.1],
       [ -4. ,   3. ,  -1. ,   1. ]])

In [104]:
np.linalg.det(matr)

-9.99999999999993

In [105]:
np.linalg.eig(matr)

EigResult(eigenvalues=array([18.01754886+0.j        , -0.07356661+0.j        ,
        2.02800888+1.85244688j,  2.02800888-1.85244688j]), eigenvectors=array([[-0.48444376+0.j        , -0.75202037+0.j        ,
        -0.31024942+0.17169189j, -0.31024942-0.17169189j],
       [-0.68044499+0.j        ,  0.26367487+0.j        ,
        -0.1032407 +0.33725028j, -0.1032407 -0.33725028j],
       [-0.42871242+0.j        ,  0.56190033+0.j        ,
         0.68714234+0.j        ,  0.68714234-0.j        ],
       [-0.34425939+0.j        , -0.22183092+0.j        ,
        -0.43417705-0.29865781j, -0.43417705+0.29865781j]]))

In [107]:
# Statistical Functions:
np.mean(a)

6.5

In [108]:
np.median(a)

6.5

In [109]:
np.var(a)

3.25

In [110]:
np.std(a)

1.8027756377319946